---
apiVersion: v1
kind: Service
metadata:
  namespace: qa
  name: ezziileave-ui
  labels:
    app: ezziileave-ui
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: ezziileave-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ezziileave-ui
  name: ezziileave-ui
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezziileave-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: ezziileave-ui
      name: ezziileave-ui
    spec:
      nodeSelector:
        env: nonprod
      dnsConfig:
        searches:
          - svc.cluster.local
        options:
          - name: ndots
            value: '2'
      containers:
      - name: app
        image: resolvepay.azurecr.io/ezziileave-ui:{{BUILDTAG}}
        imagePullPolicy: IfNotPresent