services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: resolve@2022
      POSTGRES_DB: resolve-leave
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/resolve-leave
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend   

volumes:
  pgdata:
