---
apiVersion: v1
kind: Service
metadata:
  namespace: {{Environment}} # Replace with your namespace
  name: db
  labels:
    app: db
spec:
  ports:
    - name: postgres # More descriptive port name
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: {{Environment}} # Replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate: # Use RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:latest # Consider using a specific version for production
        imagePullPolicy: IfNotPresent # Good practice
        ports:
          - containerPort: 5432
            protocol: TCP
        env:
          - name: POSTGRES_DB
            value: resolve-leave
          - name: POSTGRES_PASSWORD
            value: resolve@2022 # Consider using a Kubernetes Secret for passwords
          - name: POSTGRES_USER
            value: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pgdata
      restartPolicy: Always
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata