apiVersion: v1
kind: Service
metadata:
  namespace: qa  # Replace {{Environment}} with actual value
  name: eziileave-ui
  labels:
    app: eziileave-ui
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: eziileave-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eziileave-ui
  name: eziileave-ui
  namespace: qa  # Replace {{Environment}} with actual value
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eziileave-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: eziileave-ui
      name: eziileave-ui
    spec:
      nodeSelector:
        env: nonprod
      dnsConfig:
        searches:
          - svc.cluster.local
        options:
          - name: ndots
            value: '2'
      containers:
      - name: eziileave-ui
        image: resolvepay.azurecr.io/eziileave-ui:{{BUILDTAG}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5