---
apiVersion: v1
kind: Service
metadata:
  namespace: qa # Replace with your namespace
  name: resolve-leave-ui
  labels:
    app: resolve-leave-ui
spec:
  ports:
    - name: http # Descriptive port name
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: resolve-leave-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resolve-leave-ui
  name: resolve-leave-ui
  namespace: qa # Replace with your namespace
spec:
  replicas: 2 # Use the replica count from the second definition
  selector:
    matchLabels:
      app: resolve-leave-ui
  strategy:
    rollingUpdate: # Use RollingUpdate for better deployments
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resolve-leave-ui
    spec:
      containers:
      - name: resolve-leave-ui # Give a meaningful name to the container
        image: resolvepay.azurecr.io/qa/resolve-leave-ui:{{BUILDTAG}} # Replace with your image and tag
        imagePullPolicy: IfNotPresent # Good practice
        ports:
          - containerPort: 3000
            protocol: TCP
      restartPolicy: Always