---
apiVersion: v1
kind: Service
metadata:
  namespace: qa # Replace with your namespace
  name: resolve-ui-leave
  labels:
    app: resolve-ui-leave
spec:
  ports:
    - name: http # Descriptive port name
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: resolve-ui-leave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resolve-ui-leave
  name: resolve-ui-leave
  namespace: qa # Replace with your namespace
spec:
  replicas: 1 # Use the replica count from the second definition
  selector:
    matchLabels:
      app: resolve-ui-leave
  strategy:
    rollingUpdate: # Use RollingUpdate for better deployments
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resolve-ui-leave
    spec:
      containers:
      - name: resolve-ui-leave # Give a meaningful name to the container
        image: resolvepay.azurecr.io/resolve-ui-leave:{{BUILDTAG}} # Replace with your image and tag
        imagePullPolicy: IfNotPresent # Good practice
        ports:
          - containerPort: 3000
            protocol: TCP
      restartPolicy: Always